// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hello.sql

package repository

import (
	"context"
)

const helloWorld = `-- name: HelloWorld :one
SELECT 'Hello, World!' as message
`

func (q *Queries) HelloWorld(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, helloWorld)
	var message string
	err := row.Scan(&message)
	return message, err
}
