// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

type TicketStatus string

const (
	TicketStatusNone   TicketStatus = "none"
	TicketStatusInit   TicketStatus = "init"
	TicketStatusOpen   TicketStatus = "open"
	TicketStatusClosed TicketStatus = "closed"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type ComplaintDetail struct {
	ID          uuid.UUID   `json:"id"`
	Ticket      uuid.UUID   `json:"ticket"`
	Description string      `json:"description"`
	SenderName  string      `json:"sender_name"`
	SenderPhone *string     `json:"sender_phone"`
	SenderEmail *string     `json:"sender_email"`
	GeoLocation interface{} `json:"geo_location"`
}

type Department struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Source struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Status struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Subcategory struct {
	ID         int32  `json:"id"`
	CategoryID int32  `json:"category_id"`
	Name       string `json:"name"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Ticket struct {
	ID            uuid.UUID        `json:"id"`
	Status        TicketStatus     `json:"status"`
	Description   string           `json:"description"`
	SubcategoryID int32            `json:"subcategory_id"`
	DepartmentID  *int32           `json:"department_id"`
	Embedding     *pgvector.Vector `json:"embedding"`
	IsHidden      bool             `json:"is_hidden"`
	IsDeleted     bool             `json:"is_deleted"`
	CreatedAt     time.Time        `json:"created_at"`
}

type TicketTag struct {
	Ticket uuid.UUID `json:"ticket"`
	Tag    int32     `json:"tag"`
}
