// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitoring.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOverdueTickets = `-- name: CountOverdueTickets :one
WITH ticket_status_start AS (
    SELECT DISTINCT ON (th.ticket_id)
        th.ticket_id,
        th.created_at as status_start_date
    FROM ticket_history th
    WHERE th.action = 'status_changed'
        AND (th.new_value->>'status' = 'open' OR th.new_value->>'status' = 'init')
    ORDER BY th.ticket_id, th.created_at DESC
),
ticket_created AS (
    SELECT DISTINCT ON (th.ticket_id)
        th.ticket_id,
        th.created_at as created_date
    FROM ticket_history th
    WHERE th.action = 'created'
    ORDER BY th.ticket_id, th.created_at ASC
)
SELECT COUNT(*)
FROM tickets t
LEFT JOIN ticket_status_start tss ON tss.ticket_id = t.id
LEFT JOIN ticket_created tc ON tc.ticket_id = t.id
WHERE
    t.is_deleted = false
    AND t.is_hidden = false
    AND t.status IN ('open', 'init')
    AND GREATEST(0, EXTRACT(DAY FROM CURRENT_DATE - (COALESCE(tss.status_start_date, tc.created_date, t.created_at)::DATE + INTERVAL '7 days')))::INTEGER >= $1::INTEGER
    AND ($2::INTEGER IS NULL OR t.department_id = $2::INTEGER)
`

type CountOverdueTicketsParams struct {
	MinLostDays  int32  `json:"min_lost_days"`
	DepartmentID *int32 `json:"department_id"`
}

func (q *Queries) CountOverdueTickets(ctx context.Context, arg CountOverdueTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueTickets, arg.MinLostDays, arg.DepartmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOverdueTickets = `-- name: GetOverdueTickets :many

WITH ticket_status_start AS (
    SELECT DISTINCT ON (th.ticket_id)
        th.ticket_id,
        th.created_at as status_start_date
    FROM ticket_history th
    WHERE th.action = 'status_changed'
        AND (th.new_value->>'status' = 'open' OR th.new_value->>'status' = 'init')
    ORDER BY th.ticket_id, th.created_at DESC
),
ticket_created AS (
    SELECT DISTINCT ON (th.ticket_id)
        th.ticket_id,
        th.created_at as created_date
    FROM ticket_history th
    WHERE th.action = 'created'
    ORDER BY th.ticket_id, th.created_at ASC
)
SELECT
    t.id,
    t.description,
    t.status,
    t.subcategory_id,
    t.department_id,
    COALESCE(tss.status_start_date, tc.created_date, t.created_at) as status_start_date,
    GREATEST(0, EXTRACT(DAY FROM CURRENT_DATE - (COALESCE(tss.status_start_date, tc.created_date, t.created_at)::DATE + INTERVAL '7 days')))::INTEGER as lost_days
FROM tickets t
LEFT JOIN ticket_status_start tss ON tss.ticket_id = t.id
LEFT JOIN ticket_created tc ON tc.ticket_id = t.id
WHERE
    t.is_deleted = false
    AND t.is_hidden = false
    AND t.status IN ('open', 'init')
    AND GREATEST(0, EXTRACT(DAY FROM CURRENT_DATE - (COALESCE(tss.status_start_date, tc.created_date, t.created_at)::DATE + INTERVAL '7 days')))::INTEGER >= $1::INTEGER
    AND ($2::INTEGER IS NULL OR t.department_id = $2::INTEGER)
ORDER BY lost_days DESC
LIMIT $3::INTEGER
`

type GetOverdueTicketsParams struct {
	MinLostDays  int32  `json:"min_lost_days"`
	DepartmentID *int32 `json:"department_id"`
	Limit        int32  `json:"limit"`
}

type GetOverdueTicketsRow struct {
	ID              uuid.UUID    `json:"id"`
	Description     string       `json:"description"`
	Status          TicketStatus `json:"status"`
	SubcategoryID   int32        `json:"subcategory_id"`
	DepartmentID    *int32       `json:"department_id"`
	StatusStartDate time.Time    `json:"status_start_date"`
	LostDays        int32        `json:"lost_days"`
}

// queries/monitoring.sql
func (q *Queries) GetOverdueTickets(ctx context.Context, arg GetOverdueTicketsParams) ([]GetOverdueTicketsRow, error) {
	rows, err := q.db.Query(ctx, getOverdueTickets, arg.MinLostDays, arg.DepartmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueTicketsRow{}
	for rows.Next() {
		var i GetOverdueTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.SubcategoryID,
			&i.DepartmentID,
			&i.StatusStartDate,
			&i.LostDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
