// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statistics.sql

package repository

import (
	"context"
)

const getCategoryStatistics = `-- name: GetCategoryStatistics :many
SELECT 
    c.id,
    c.name,
    COUNT(t.id) as ticket_count
FROM categories c
LEFT JOIN subcategories sc ON sc.category_id = c.id
LEFT JOIN tickets t ON t.subcategory_id = sc.id 
    AND t.is_deleted = false 
    AND t.is_hidden = false
GROUP BY c.id, c.name
ORDER BY ticket_count DESC, c.name
`

type GetCategoryStatisticsRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	TicketCount int64  `json:"ticket_count"`
}

func (q *Queries) GetCategoryStatistics(ctx context.Context) ([]GetCategoryStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getCategoryStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryStatisticsRow{}
	for rows.Next() {
		var i GetCategoryStatisticsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TicketCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatisticsSummary = `-- name: GetStatisticsSummary :one
SELECT
    COUNT(*) FILTER (WHERE is_deleted = false AND is_hidden = false) AS total,

    COUNT(*) FILTER (
        WHERE status = 'closed'
        AND is_deleted = false
        AND is_hidden = false
    ) AS resolved,

    COUNT(*) FILTER (
        WHERE status = 'open'
        AND is_deleted = false
        AND is_hidden = false
    ) AS in_progress,

    COUNT(DISTINCT department_id) FILTER (
        WHERE department_id IS NOT NULL
        AND is_deleted = false
        AND is_hidden = false
    ) AS active_executors
FROM tickets
`

type GetStatisticsSummaryRow struct {
	Total           int64 `json:"total"`
	Resolved        int64 `json:"resolved"`
	InProgress      int64 `json:"in_progress"`
	ActiveExecutors int64 `json:"active_executors"`
}

func (q *Queries) GetStatisticsSummary(ctx context.Context) (GetStatisticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStatisticsSummary)
	var i GetStatisticsSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Resolved,
		&i.InProgress,
		&i.ActiveExecutors,
	)
	return i, err
}
