// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const countTickets = `-- name: CountTickets :one
SELECT COUNT(*) FROM tickets
WHERE is_hidden = false
`

func (q *Queries) CountTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTickets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsByStatus = `-- name: CountTicketsByStatus :one
SELECT COUNT(*) FROM tickets
WHERE status = $1 AND is_hidden = false
`

type CountTicketsByStatusParams struct {
	Status TicketStatus `json:"status"`
}

func (q *Queries) CountTicketsByStatus(ctx context.Context, arg CountTicketsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsByStatus, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO complaint_details (
  ticket,
  description,
  sender_name,
  sender_phone,
  sender_email,
  geo_location
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, ticket, description, sender_name, sender_phone, sender_email, geo_location
`

type CreateComplaintParams struct {
	Ticket      uuid.UUID   `json:"ticket"`
	Description string      `json:"description"`
	SenderName  string      `json:"sender_name"`
	SenderPhone *string     `json:"sender_phone"`
	SenderEmail *string     `json:"sender_email"`
	GeoLocation interface{} `json:"geo_location"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (ComplaintDetail, error) {
	row := q.db.QueryRow(ctx, createComplaint,
		arg.Ticket,
		arg.Description,
		arg.SenderName,
		arg.SenderPhone,
		arg.SenderEmail,
		arg.GeoLocation,
	)
	var i ComplaintDetail
	err := row.Scan(
		&i.ID,
		&i.Ticket,
		&i.Description,
		&i.SenderName,
		&i.SenderPhone,
		&i.SenderEmail,
		&i.GeoLocation,
	)
	return i, err
}

const createTicketWithDefaults = `-- name: CreateTicketWithDefaults :one

INSERT INTO tickets (
    description,
    subcategory_id,
    department_id,
    embedding
) VALUES (
    $1,
    $2, 
    $3, 
    $4
) RETURNING id, status, description, is_hidden, subcategory_id, department_id, embedding, created_at
`

type CreateTicketWithDefaultsParams struct {
	Description   string           `json:"description"`
	SubcategoryID int32            `json:"subcategory_id"`
	DepartmentID  *int32           `json:"department_id"`
	Embedding     *pgvector.Vector `json:"embedding"`
}

// queries/tickets.sql
func (q *Queries) CreateTicketWithDefaults(ctx context.Context, arg CreateTicketWithDefaultsParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicketWithDefaults,
		arg.Description,
		arg.SubcategoryID,
		arg.DepartmentID,
		arg.Embedding,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Description,
		&i.IsHidden,
		&i.SubcategoryID,
		&i.DepartmentID,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

type DeleteTicketParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteTicket(ctx context.Context, arg DeleteTicketParams) error {
	_, err := q.db.Exec(ctx, deleteTicket, arg.ID)
	return err
}

const getDetailsForTicket = `-- name: GetDetailsForTicket :many
SELECT
  id,
  description,
  sender_name,
  sender_phone,
  sender_email,
  geo_location
FROM complaint_details
WHERE ticket = $1
`

type GetDetailsForTicketParams struct {
	Ticket uuid.UUID `json:"ticket"`
}

type GetDetailsForTicketRow struct {
	ID          uuid.UUID   `json:"id"`
	Description string      `json:"description"`
	SenderName  string      `json:"sender_name"`
	SenderPhone *string     `json:"sender_phone"`
	SenderEmail *string     `json:"sender_email"`
	GeoLocation interface{} `json:"geo_location"`
}

func (q *Queries) GetDetailsForTicket(ctx context.Context, arg GetDetailsForTicketParams) ([]GetDetailsForTicketRow, error) {
	rows, err := q.db.Query(ctx, getDetailsForTicket, arg.Ticket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDetailsForTicketRow{}
	for rows.Next() {
		var i GetDetailsForTicketRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.SenderName,
			&i.SenderPhone,
			&i.SenderEmail,
			&i.GeoLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT
  id,
  status,
  description,
  is_hidden,
  subcategory_id,
  department_id,
  created_at
FROM tickets
WHERE id = $1 AND is_hidden = false
`

type GetTicketParams struct {
	ID uuid.UUID `json:"id"`
}

type GetTicketRow struct {
	ID            uuid.UUID    `json:"id"`
	Status        TicketStatus `json:"status"`
	Description   string       `json:"description"`
	IsHidden      bool         `json:"is_hidden"`
	SubcategoryID int32        `json:"subcategory_id"`
	DepartmentID  *int32       `json:"department_id"`
	CreatedAt     time.Time    `json:"created_at"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ID)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Description,
		&i.IsHidden,
		&i.SubcategoryID,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, status, description, is_hidden, subcategory_id, department_id, embedding, created_at FROM tickets
WHERE is_hidden = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Description,
			&i.IsHidden,
			&i.SubcategoryID,
			&i.DepartmentID,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTicketsByEmbedding = `-- name: SearchTicketsByEmbedding :many
SELECT 
  id,
  status,
  description,
  is_hidden,
  subcategory_id,
  department_id,
  created_at
FROM tickets
WHERE is_hidden = false
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchTicketsByEmbeddingParams struct {
	Embedding *pgvector.Vector `json:"embedding"`
	Limit     int32            `json:"limit"`
}

type SearchTicketsByEmbeddingRow struct {
	ID            uuid.UUID    `json:"id"`
	Status        TicketStatus `json:"status"`
	Description   string       `json:"description"`
	IsHidden      bool         `json:"is_hidden"`
	SubcategoryID int32        `json:"subcategory_id"`
	DepartmentID  *int32       `json:"department_id"`
	CreatedAt     time.Time    `json:"created_at"`
}

func (q *Queries) SearchTicketsByEmbedding(ctx context.Context, arg SearchTicketsByEmbeddingParams) ([]SearchTicketsByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchTicketsByEmbedding, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTicketsByEmbeddingRow{}
	for rows.Next() {
		var i SearchTicketsByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Description,
			&i.IsHidden,
			&i.SubcategoryID,
			&i.DepartmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET 
    status = COALESCE($2, status),
    description = COALESCE($3, description),
    subcategory_id = COALESCE($4, subcategory_id),
    department_id = COALESCE($5, department_id),
    embedding = COALESCE($6, embedding)
WHERE id = $1 AND is_hidden = false
RETURNING id, status, description, is_hidden, subcategory_id, department_id, embedding, created_at
`

type UpdateTicketParams struct {
	ID            uuid.UUID        `json:"id"`
	Status        TicketStatus     `json:"status"`
	Description   string           `json:"description"`
	SubcategoryID int32            `json:"subcategory_id"`
	DepartmentID  *int32           `json:"department_id"`
	Embedding     *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Status,
		arg.Description,
		arg.SubcategoryID,
		arg.DepartmentID,
		arg.Embedding,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Description,
		&i.IsHidden,
		&i.SubcategoryID,
		&i.DepartmentID,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}
