// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    title,
    description,
    location,
    embedding
)
VALUES (
    $1,
    $2,
    ST_SetSRID(
        ST_MakePoint(
            $3,
            $4
        ),
        4326
    )::geography,
    $5
)
RETURNING id, title, description, location, embedding, created_at
`

type CreateTicketParams struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Longitude   interface{}      `json:"longitude"`
	Latitude    interface{}      `json:"latitude"`
	Embedding   *pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Title,
		arg.Description,
		arg.Longitude,
		arg.Latitude,
		arg.Embedding,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const searchTicketsByMeaning = `-- name: SearchTicketsByMeaning :many
SELECT
    id,
    title,
    description,
    embedding <=> $1 AS distance
FROM tickets
ORDER BY distance ASC
`

type SearchTicketsByMeaningParams struct {
	QueryEmbedding *pgvector.Vector `json:"query_embedding"`
}

type SearchTicketsByMeaningRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Distance    interface{} `json:"distance"`
}

func (q *Queries) SearchTicketsByMeaning(ctx context.Context, arg SearchTicketsByMeaningParams) ([]SearchTicketsByMeaningRow, error) {
	rows, err := q.db.Query(ctx, searchTicketsByMeaning, arg.QueryEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTicketsByMeaningRow{}
	for rows.Next() {
		var i SearchTicketsByMeaningRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
