// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package repository

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    title,
    description,
    location,
    embedding
)
VALUES (
    $1,
    $2,
    ST_SetSRID(
        ST_MakePoint(
            $3,
            $4
        ),
        4326
    )::geography,
    $5
)
RETURNING id, title, description, location, embedding, created_at
`

type CreateTicketParams struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Longitude   interface{}      `json:"longitude"`
	Latitude    interface{}      `json:"latitude"`
	Embedding   *pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Title,
		arg.Description,
		arg.Longitude,
		arg.Latitude,
		arg.Embedding,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}
